'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import { Area, AreaChart, Bar, BarChart, Cell, CartesianGrid, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { ArrowUpRight, Activity, FlaskConical, Shield, Target, Download, SlidersHorizontal, Info } from 'lucide-react'
import { buildEdgeAnalytics, simulateR } from '@/lib/edgeAnalytics'
import { formatR } from '@/lib/rMultiple'
import s from './EdgeLab.module.css'

const GOLD = '#E8C66A', GREEN = '#4adea0', RED = '#fb8190'
const tone = n => n == null ? undefined : n < 0 ? RED : n > 0 ? GREEN : GOLD
const number = n => n == null ? '—' : n === Infinity ? '∞' : n.toFixed(2)
const percent = n => n == null ? '—' : `${n.toFixed(1)}%`
const DIMENSIONS = [['playbook', 'Playbook'], ['symbol', 'Symbol'], ['session', 'Session'], ['side', 'Direction'], ['weekday', 'Weekday'], ['emotion', 'Focus score'], ['tags', 'Tags']]
function ChartTip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  return <div className={s.tooltip}><strong>{payload[0]?.payload?.symbol ? `${payload[0].payload.symbol} · ${payload[0].payload.date}` : `Trade ${label}`}</strong>{payload.map(p => <div key={p.dataKey} style={{ color: p.color }}>{p.name}: {Array.isArray(p.value) ? p.value.map(x => formatR(x)).join(' to ') : formatR(p.value)}</div>)}</div>
}
function Axes() { return <><CartesianGrid vertical={false} stroke="var(--border-subtle)" strokeDasharray="3 5" /><XAxis dataKey="n" tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} minTickGap={25} /><YAxis width={55} tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} tickFormatter={v => `${Number(v.toFixed(1))}R`} /><ReferenceLine y={0} stroke="var(--text-muted)" strokeDasharray="3 5" /></> }
function Metric({ label, value, detail, color }) { return <div className={s.metric}><span>{label}</span><strong style={{ color }}>{value}</strong><small>{detail}</small></div> }
function Panel({ title, subtitle, children, action, className = '' }) { return <section className={`${s.panel} ${className}`}><div className={s.panelHead}><div><h3>{title}</h3><p>{subtitle}</p></div>{action}</div>{children}</section> }
function exportRows(rows) {
  const escape = x => `"${String(x ?? '').replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`
  const body = [['Segment', 'Trades', 'Total R', 'Expectancy R', 'Win rate % (all)', 'Profit factor R', 'Max drawdown R'], ...rows.map(r => [r.name, r.n, r.total, r.avg, r.winRate, r.profitFactor, r.drawdown])].map(row => row.map(escape).join(',')).join('\r\n')
  const url = URL.createObjectURL(new Blob([body], { type: 'text/csv;charset=utf-8;' })), a = document.createElement('a')
  a.href = url; a.download = 'edge-lab-segments.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)
}
export default function EdgeLab({ trades, playbooks }) {
  const [window, setWindow] = useState(20), [dimension, setDimension] = useState('playbook'), [minSample, setMinSample] = useState(5)
  const [view, setView] = useState('cumulative'), [horizon, setHorizon] = useState(50), [cost, setCost] = useState(0), [seed, setSeed] = useState(73421)
  const [selectedCell, setSelectedCell] = useState(null)
  const edge = useMemo(() => buildEdgeAnalytics(trades, { window, dimension, playbooks, minSample }), [trades, window, dimension, playbooks, minSample])
  const simulation = useMemo(() => simulateR(edge.values, { horizon, cost, seed }), [edge.values, horizon, cost, seed])
  const { stats: a, interval } = edge
  const qualified = edge.rows.filter(r => r.qualified), best = qualified[0], worst = [...qualified].sort((x, y) => x.avg - y.avg)[0]
  const coverage = edge.closed ? a.n / edge.closed * 100 : 0
  const delta = edge.recent.n === window && edge.prior.n === window ? edge.recent.avg - edge.prior.avg : null
  const distribution = [
    ['≤ −2', r => r <= -2], ['−2 to −1', r => r > -2 && r <= -1], ['−1 to 0', r => r > -1 && r < 0], ['0', r => r === 0], ['0 to 1', r => r > 0 && r < 1], ['1 to 2', r => r >= 1 && r < 2], ['2 to 3', r => r >= 2 && r < 3], ['≥ 3', r => r >= 3],
  ].map(([name, test], i) => ({ name, count: edge.values.filter(test).length, color: i < 3 ? RED : i === 3 ? GOLD : GREEN }))
  const selected = selectedCell ? edge.timing.get(selectedCell) : null
  return <div className={s.lab}>
    <section className={s.hero}>
      <div><div className={s.eyebrow}><FlaskConical size={15} /> THE EDGE LAB <span>R-FIRST RESEARCH</span></div><h2>Know what earns.<br /><em>Understand what lasts.</em></h2><p>Separate repeatable execution from a good run. Study your edge in units of risk, then challenge it.</p><div className={s.heroMeta}><span><Activity size={14} /> {a.n} R trades</span><span>{edge.closed - a.n} excluded · missing R or date</span><span>Realized outcomes</span></div></div>
      <div className={s.evidence}><span className={s.eyebrow}>EXPECTANCY EVIDENCE</span><strong>{a.n < 5 ? 'Collecting data' : interval?.low > 0 ? 'Positive sample' : interval?.high < 0 ? 'Negative sample' : 'Not yet conclusive'}</strong><p>{interval ? `95% bootstrap interval: ${formatR(interval.low)} to ${formatR(interval.high)} per trade.` : 'Log at least 5 closed trades with R to estimate an interval.'}</p><div className={s.coverage}><span style={{ width: `${coverage}%` }} /></div><small>{coverage.toFixed(0)}% R coverage · {a.n < 30 ? 'Small sample: conclusions are fragile.' : 'Historical evidence, not proof of future returns.'}</small></div>
    </section>

    {!a.n ? <section className={s.empty}><Target size={32} /><h3>Your research starts with one R.</h3><p>Record each closed trade’s result as a multiple of its initial planned risk. Missing R is excluded, never counted as zero.</p><Link href="/journal" className={s.button}>Review your journal <ArrowUpRight size={16} /></Link></section> : <>
    <div className={s.metrics}>
      <Metric label="NET PERFORMANCE" value={formatR(a.total)} detail={`${a.n} closed trades with R`} color={tone(a.total)} />
      <Metric label="EXPECTANCY / TRADE" value={formatR(a.avg)} detail={`Median ${formatR(a.median)}`} color={tone(a.avg)} />
      <Metric label="R PROFIT FACTOR" value={number(a.profitFactor)} detail="Gross winning R ÷ gross losing R" />
      <Metric label="MAX DRAWDOWN" value={formatR(a.drawdown)} detail={`Current ${formatR(a.currentDrawdown)}`} color={RED} />
    </div>
    <div className={s.mainGrid}>
      <Panel title="The shape of your edge" subtitle={view === 'rolling' ? `Mean R of the last ${window} trades; starts after a full window.` : view === 'drawdown' ? 'Distance below the previous cumulative R high. Baseline starts at zero.' : 'Cumulative realized R, in chronological order. Every trade carries equal risk weight.'} action={<div className={s.switches}>{[['cumulative', 'Equity'], ['drawdown', 'Drawdown'], ['rolling', 'Rolling R']].map(([key, label]) => <button key={key} aria-pressed={view === key} onClick={() => setView(key)}>{label}</button>)}</div>}>
        <div className={s.chart} role="img" aria-label={`${view} chart for ${a.n} trades. Total ${formatR(a.total)}, max drawdown ${formatR(a.drawdown)}.`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={edge.curve} margin={{ top: 20, right: 12, bottom: 5, left: 0 }}><defs><linearGradient id="edgeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={view === 'drawdown' ? RED : GOLD} stopOpacity={.28} /><stop offset="100%" stopColor={GOLD} stopOpacity={.01} /></linearGradient></defs>{Axes()}<Tooltip content={<ChartTip />} /><Area isAnimationActive={false} type="linear" dataKey={view} name={view === 'rolling' ? 'Rolling expectancy' : view === 'drawdown' ? 'Drawdown' : 'Cumulative R'} stroke={view === 'drawdown' ? RED : GOLD} strokeWidth={2.5} fill="url(#edgeFill)" /></AreaChart></ResponsiveContainer></div>
        <div className={s.chartFooter}><span>Trade sequence →</span><label>Rolling window <select value={window} onChange={e => setWindow(Number(e.target.value))}>{[10, 20, 30, 50].map(n => <option key={n} value={n}>{n} trades</option>)}</select></label></div>
      </Panel>
      <Panel title="Edge anatomy" subtitle="The numbers behind your expectancy.">
        <div className={s.anatomy}><div><span>Average winner</span><strong style={{ color: GREEN }}>{formatR(a.avgWin)}</strong></div><div><span>Average loser</span><strong style={{ color: RED }}>{formatR(a.avgLoss)}</strong></div><div><span>Payoff ratio</span><strong>{number(a.payoff)}{a.payoff != null ? '×' : ''}</strong></div><div><span>Win rate · wins + losses</span><strong>{percent(a.decidedWinRate)}</strong></div><div><span>Break-even win rate</span><strong>{percent(a.breakEvenRate)}</strong></div><div><span>Breakeven trades</span><strong>{a.breakevens}</strong></div></div>
        <div className={s.note}><Info size={15} /><span>Expectancy includes all R trades, including 0R. Break-even rate uses the observed average winner and loser, excluding 0R.</span></div>
      </Panel>
    </div>
    <div className={s.sectionHeading}><div><span className={s.eyebrow}>01 / FIND THE CONDITIONS</span><h2>Where your edge lives</h2></div><span>Compare expectancy, not just total profit.</span></div>
    <Panel title="Segment explorer" subtitle="Ranked by R per trade. The sample floor flags thin evidence; it does not establish significance." action={<button className={s.button} onClick={() => exportRows(edge.rows)}><Download size={15} /> Export CSV</button>}>
      <div className={s.explorerControls}><div className={s.switches}>{DIMENSIONS.map(([key, label]) => <button key={key} aria-pressed={dimension === key} onClick={() => setDimension(key)}>{label}</button>)}</div><label>Sample floor<select value={minSample} onChange={e => setMinSample(Number(e.target.value))}>{[5, 10, 20, 30, 50].map(n => <option key={n} value={n}>{n} trades</option>)}</select></label></div>
      <div className={s.tableWrap}><table><thead><tr><th>Segment</th><th>Sample</th><th>Expectancy</th><th>Total R</th><th>Win rate¹</th><th>R factor</th><th>Max DD</th><th>Evidence</th></tr></thead><tbody>{edge.rows.map(r => <tr key={r.name}><th>{r.name}</th><td>{r.n}</td><td style={{ color: tone(r.avg) }}><strong>{formatR(r.avg)}</strong></td><td>{formatR(r.total)}</td><td>{percent(r.winRate)}</td><td>{number(r.profitFactor)}</td><td style={{ color: RED }}>{formatR(r.drawdown)}</td><td><span className={`${s.badge} ${r.qualified ? s.qualified : ''}`}>{r.qualified ? 'Meets floor' : 'Small sample'}</span></td></tr>)}</tbody></table></div><p className={s.footnote}>¹ Wins ÷ all trades, including 0R. {dimension === 'tags' ? 'Tags overlap: a trade may appear in multiple rows. Do not sum rows.' : 'Unlabeled trades remain in the comparison.'} Comparing many groups can surface patterns by chance. Validate on new trades.</p>
    </Panel>
    <div className={s.insightGrid}>
      <div className={s.insight}><Target size={19} /><span>RESEARCH CANDIDATE</span><h3>{best && best.avg > 0 ? best.name : 'Keep building the sample'}</h3><p>{best && best.avg > 0 ? `${formatR(best.avg)} per trade across ${best.n} trades. Define this setup before testing it on the next sample.` : 'No positive segment meets your sample floor. Keep logging consistently before narrowing your playbook.'}</p></div>
      <div className={s.insight}><Shield size={19} /><span>REVIEW CANDIDATE</span><h3>{worst && worst.avg < 0 ? worst.name : 'No qualifying negative segment'}</h3><p>{worst && worst.avg < 0 ? `${formatR(worst.total)} across ${worst.n} trades. Review execution and market conditions before changing a rule.` : 'A clean comparison today does not rule out a future drawdown. Keep the same review criteria.'}</p></div>
      <div className={s.insight}><Activity size={19} /><span>RECENT MOMENTUM</span><h3>{delta == null ? 'Two windows needed' : `${formatR(delta)} / trade`}</h3><p>{delta == null ? `Log ${window * 2} R trades to compare two non-overlapping ${window}-trade windows.` : `Last ${window}: ${formatR(edge.recent.avg)}. Previous ${window}: ${formatR(edge.prior.avg)}. A change in conditions or execution is worth reviewing.`}</p></div>
    </div>
    <div className={s.sectionHeading}><div><span className={s.eyebrow}>02 / CHALLENGE THE RESULT</span><h2>How resilient is your edge?</h2></div></div>
    <div className={s.twoGrid}>
      <Panel title="Outcome distribution" subtitle="Count of trades in each R bucket. Large losses and rare winners deserve context."><div className={s.smallChart} role="img" aria-label="Trade counts grouped by R outcome"><ResponsiveContainer width="100%" height="100%"><BarChart data={distribution}><CartesianGrid vertical={false} stroke="var(--border-subtle)" /><XAxis dataKey="name" tick={{ fill: 'var(--text-muted)', fontSize: 10 }} interval={0} axisLine={false} tickLine={false} /><YAxis width={30} allowDecimals={false} tick={{ fill: 'var(--text-muted)', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)', borderRadius: 10 }} formatter={v => [v, 'Trades']} labelFormatter={v => `${v}R`} /><Bar dataKey="count" isAnimationActive={false} radius={[4, 4, 0, 0]}>{distribution.map(b => <Cell key={b.name} fill={b.color} fillOpacity={.8} />)}</Bar></BarChart></ResponsiveContainer></div></Panel>
      <Panel title="Robustness checks" subtitle="Look for dependence on one winner or one period."><div className={s.anatomy}><div><span>Expectancy without best trade</span><strong style={{ color: tone(a.withoutBest) }}>{formatR(a.withoutBest)}</strong></div><div><span>First half <small>({edge.first.n} trades)</small></span><strong style={{ color: tone(edge.first.avg) }}>{formatR(edge.first.avg)}</strong></div><div><span>Second half <small>({edge.second.n} trades)</small></span><strong style={{ color: tone(edge.second.avg) }}>{formatR(edge.second.avg)}</strong></div><div><span>Average worst 10% <small>(rounded up)</small></span><strong style={{ color: tone(a.tailLoss) }}>{formatR(a.tailLoss)}</strong></div><div><span>Longest losing streak</span><strong>{a.maxLossStreak} trades</strong></div><div><span>Longest time below peak</span><strong>{a.longestRecovery} trades</strong></div></div><p className={s.footnote}>Halves are chronological and descriptive, not an independent holdout. Time below peak includes any ongoing recovery.</p></Panel>
    </div>
    <Panel title="Path simulator" subtitle="500 resampled paths. Explore the range of outcomes your recorded R distribution can produce." action={<span className={s.badge}><FlaskConical size={13} /> EXPERIMENT</span>}>
      <div className={s.simControls}><label>Future trades<select value={horizon} onChange={e => setHorizon(Number(e.target.value))}>{[25, 50, 100, 200].map(n => <option key={n} value={n}>{n} trades</option>)}</select></label><label>Extra friction / trade<select value={cost} onChange={e => setCost(Number(e.target.value))}>{[0, .02, .05, .1, .2].map(n => <option key={n} value={n}>{n.toFixed(2)}R</option>)}</select></label><button className={s.button} onClick={() => setSeed(n => n + 1)} disabled={!simulation}>Resample paths <Activity size={15} /></button></div>
      {simulation ? <><div className={s.chart} role="img" aria-label={`Simulated median ${formatR(simulation.end.median)}, 90% ending range ${simulation.end.band.map(x => formatR(x)).join(' to ')}`}><ResponsiveContainer width="100%" height="100%"><ComposedChart data={simulation.curve}>{Axes()}<Tooltip content={<ChartTip />} /><Area dataKey="band" name="5th–95th percentile" stroke="none" fill={GOLD} fillOpacity={.15} isAnimationActive={false} /><Line dataKey="median" name="Median path" stroke={GOLD} strokeWidth={2} dot={false} isAnimationActive={false} /></ComposedChart></ResponsiveContainer></div><div className={s.simMetrics}><Metric label="MEDIAN ENDING R" value={formatR(simulation.end.median)} /><Metric label="90% ENDING RANGE" value={`${formatR(simulation.end.band[0])} → ${formatR(simulation.end.band[1])}`} /><Metric label="PATHS ENDING BELOW 0R" value={percent(simulation.lossChance)} /><Metric label="95TH PERCENTILE MAX DD" value={formatR(-simulation.drawdown95)} /></div></> : <p className={s.empty}>At least 5 eligible R trades are needed to simulate paths.</p>}
      <div className={s.note}><Info size={16} /><span>Illustrative, not a forecast. Trades are sampled independently with replacement; streak clustering, changing regimes and unobserved losses are not modeled. The band is pointwise, not a bound for an entire path. Extra friction is subtracted from logged R; existing costs are not inferred.</span></div>
    </Panel>
    <div className={s.sectionHeading}><div><span className={s.eyebrow}>03 / REFINE EXECUTION</span><h2>Turn observations into a review</h2></div></div>
    <div className={s.twoGrid}>
      <Panel title="Entry timing map" subtitle="Average R by entry weekday and 4-hour block, in your browser’s local timezone.">
        <div className={s.heatWrap}><div className={s.heatmap}><span />{['00–04', '04–08', '08–12', '12–16', '16–20', '20–24'].map(h => <span key={h}>{h}</span>)}{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, d) => <div className={s.heatRow} key={day}><span>{day}</span>{Array.from({ length: 6 }, (_, block) => { const key = `${d}-${block}`, rs = edge.timing.get(key), avg = rs ? rs.reduce((x, y) => x + y, 0) / rs.length : null; return <button key={key} aria-pressed={selectedCell === key} aria-label={`${day} ${block * 4}:00, ${rs?.length || 0} trades, average ${formatR(avg)}`} title={`${rs?.length || 0} trades · ${formatR(avg)}`} onClick={() => setSelectedCell(key)} style={{ background: avg == null ? 'var(--bg-elevated)' : avg > 0 ? `rgba(74,222,160,${Math.min(.32, .08 + Math.abs(avg) * .08)})` : avg < 0 ? `rgba(251,129,144,${Math.min(.32, .08 + Math.abs(avg) * .08)})` : 'var(--bg-elevated)', color: tone(avg) }}>{avg == null ? '—' : `${avg > 0 ? '+' : ''}${avg.toFixed(1)}`}</button> })}</div>)}</div></div><p className={s.footnote} aria-live="polite">{selectedCell ? `${['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][Number(selectedCell.split('-')[0])]} ${Number(selectedCell.split('-')[1]) * 4}:00–${Number(selectedCell.split('-')[1]) * 4 + 4}:00 · ${selected?.length || 0} trades${selected?.length ? ` · ${formatR(selected.reduce((x, y) => x + y, 0) / selected.length)} expectancy. ${selected.length < minSample ? 'Small sample.' : 'Meets sample floor.'}` : ''}` : 'Select a cell to inspect its sample. Empty cells mean no recorded trades.'}</p>
      </Panel>
      <Panel title="Execution review" subtitle="Observed outcomes associated with your recorded mistakes.">
        {edge.mistakes.length ? <div className={s.mistakes}>{edge.mistakes.slice(0, 6).map(m => <div key={m.name}><div><strong>{m.name}</strong><small>{m.n} trades · {formatR(m.avg)} average</small></div><strong style={{ color: tone(m.total) }}>{formatR(m.total)}</strong></div>)}</div> : <div className={s.quiet}><Shield size={25} /><h4>No mistake labels in this sample</h4><p>Add mistake tags in your journal to study execution patterns here.</p><Link href="/journal">Open journal <ArrowUpRight size={14} /></Link></div>}
        <p className={s.footnote}>Labels may overlap. These are associated outcomes, not recoverable profit or proof of causation. {a.belowOne} trades finished below −1R; inspect gaps, costs and execution in the journal.</p>
      </Panel>
    </div>
    <Panel title="Inspect the underlying trades" subtitle="The latest 12 eligible trades in this filtered sample. Open a trade to review its risk and execution.">
      <div className={s.tableWrap}><table><thead><tr><th>Trade</th><th>Realized</th><th>Direction</th><th>Result</th><th>Review</th></tr></thead><tbody>{edge.eligible.slice(-12).reverse().map(t => <tr key={t.id}><th>{t.symbol}</th><td>{new Date(t.occurredAt || t.exitDate || t.entryDate).toLocaleDateString()}</td><td>{t.side}</td><td style={{ color: tone(Number(t.rMultiple)) }}>{formatR(Number(t.rMultiple))}</td><td><Link href={`/journal/${encodeURIComponent(t.id)}`} className={s.tradeLink} aria-label={`Review ${t.symbol} trade on ${new Date(t.occurredAt || t.exitDate || t.entryDate).toLocaleDateString()}`}>Open trade <ArrowUpRight size={13} /></Link></td></tr>)}</tbody></table></div>
    </Panel>
    <section className={s.review}><div className={s.eyebrow}><SlidersHorizontal size={15} /> YOUR NEXT REVIEW</div><h3>One hypothesis. A fresh sample. The same rules.</h3><p>Choose one observation above. Write down the setup, entry, invalidation and review date before the next trades. Compare the next sample with these results before promoting a pattern into a rule.</p><Link href="/playbooks" className={s.button}>Refine a playbook <ArrowUpRight size={15} /></Link></section>
    </>}
    <details className={s.method}><summary>Data definitions & research assumptions</summary><p>1R is the initial planned risk of a trade. This lab uses your explicitly logged R; it does not estimate missing R from P&L or assume whether fees are included. Only visible, closed trades with a finite R and valid realization date count. Realization uses occurredAt, then exit date, then entry date. Date filters use your local calendar day.</p><p>Expectancy is the arithmetic mean of R, including breakevens. R profit factor is positive R divided by absolute negative R; ∞ means winners with no losses, and — means no meaningful ratio. Drawdown starts from 0R. The 95% expectancy interval uses 800 IID percentile bootstrap samples and requires 5 trades; small or dependent samples can make it unreliable. A positive interval is not a probability of future profit. The simulator uses 500 independent resampled paths. No metric here guarantees an edge.</p></details>
  </div>
}
